/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PhoneCallsPanel.java
 *
 * Created on Nov 24, 2010, 3:15:17 PM
 */

package com.wordpress.salaboy.emergencyservice.tasklists;

import com.wordpress.salaboy.emergencyservice.tasklists.refreshhelpers.UIJTableRefreshManager;
import com.wordpress.salaboy.emergencyservice.tasklists.refreshhelpers.Refreshable;
import com.wordpress.salaboy.emergencyservice.main.UserTaskListUI;
import com.wordpress.salaboy.emergencyservice.taskforms.EmergencyMinimalQuestionnaireTaskFormPanel;
import com.wordpress.salaboy.call.CallManager;
import com.wordpress.salaboy.call.IncomingCallListener;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;
import org.example.ws_ht.api.wsdl.IllegalArgumentFault;
import org.example.ws_ht.api.wsdl.IllegalStateFault;
import com.wordpress.salaboy.model.Call;
import org.example.ws_ht.api.TTaskAbstract;

/**
 * @author salaboy
 * @author esteban
 */
public class IncomingPhoneCallsTaskListPanel extends javax.swing.JPanel implements Refreshable {

    private UserTaskListUI parent;

    //the list of call tasks
    private List<TTaskAbstract> taskAbstracts;
    
    /** Creates new form PhoneCallsPanel */
    public IncomingPhoneCallsTaskListPanel(UserTaskListUI parent) {
        this.parent = parent;
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        refreshJButton = new javax.swing.JButton();
        chk_autoRefresh = new javax.swing.JCheckBox();
        ftxt_refreshSeconds = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        phoneCallsJScrollPane = new javax.swing.JScrollPane();
        incomingPhoneCallsJTable = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Incoming Phone Calls Task List", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        setName("Phone Operator "); // NOI18N
        setPreferredSize(new java.awt.Dimension(300, 440));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actions", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        chk_autoRefresh.setText("auto refresh");
        chk_autoRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_autoRefreshActionPerformed(evt);
            }
        });

        ftxt_refreshSeconds.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        ftxt_refreshSeconds.setText("3");

        jLabel1.setText("secs");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(refreshJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxt_refreshSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chk_autoRefresh)
                .addContainerGap(5, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshJButton)
                    .addComponent(ftxt_refreshSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(chk_autoRefresh))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tasks List", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel2.setAlignmentX(0.3F);
        jPanel2.setAlignmentY(0.3F);

        incomingPhoneCallsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id","Incoming Call",
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Number.class,
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        }
    );
    incomingPhoneCallsJTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
    incomingPhoneCallsJTable.getTableHeader().setReorderingAllowed(false);
    incomingPhoneCallsJTable.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            incomingPhoneCallsJTablerowClick(evt);
        }
    });
    phoneCallsJScrollPane.setViewportView(incomingPhoneCallsJTable);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(phoneCallsJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(phoneCallsJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, 0, 288, Short.MAX_VALUE)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    }// </editor-fold>//GEN-END:initComponents

    private void incomingPhoneCallsJTablerowClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incomingPhoneCallsJTablerowClick
        
        int selected = incomingPhoneCallsJTable.rowAtPoint(evt.getPoint());
        String id = this.taskAbstracts.get(selected).getId();
        this.callSelected(id);
        
    }//GEN-LAST:event_incomingPhoneCallsJTablerowClick

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        this.refresh();
}//GEN-LAST:event_refreshJButtonActionPerformed

    private void chk_autoRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_autoRefreshActionPerformed
       if(chk_autoRefresh.isSelected()){
        UIJTableRefreshManager.start(chk_autoRefresh, Integer.valueOf(ftxt_refreshSeconds.getText()), this); 
       }
       
    }//GEN-LAST:event_chk_autoRefreshActionPerformed

  
   
    
    
    private JDialog callPopup;
    
    public void callSelected(String id) {
        
        EmergencyMinimalQuestionnaireTaskFormPanel emergencyMinimalQ = new EmergencyMinimalQuestionnaireTaskFormPanel(this,this.parent.getTaskClient(), id);
        callPopup = new JDialog(this.parent, "Ask For Emergency Information",true);
        callPopup.add(emergencyMinimalQ);
        this.callPopup.setSize(320, 470);
        this.callPopup.setVisible(true);
        this.callPopup.requestFocus();
    }
    
    public void hideDialog(){
        this.callPopup.setVisible(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chk_autoRefresh;
    private javax.swing.JFormattedTextField ftxt_refreshSeconds;
    private javax.swing.JTable incomingPhoneCallsJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane phoneCallsJScrollPane;
    private javax.swing.JButton refreshJButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void refresh() {

        
        try {
            taskAbstracts = this.parent.getTaskClient().getMyTaskAbstracts("", "operator", "", null, "", "", "", 0, 0);
        } catch (IllegalArgumentFault ex) {
            Logger.getLogger(IncomingPhoneCallsTaskListPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalStateFault ex) {
            Logger.getLogger(IncomingPhoneCallsTaskListPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        DefaultTableModel tableModel = ((DefaultTableModel)incomingPhoneCallsJTable.getModel());
        
        int rowCount = tableModel.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            tableModel.removeRow(0);
        }
        
        int i = 0;
        for (TTaskAbstract taskAbstract : taskAbstracts) {
            String name = taskAbstract.getName().toString();
            tableModel.addRow(new Object[]{++i,name});
        }
        
        incomingPhoneCallsJTable.getColumnModel().getColumn(0).setMaxWidth(25);
        
    }

}
