package phoneCallPrimaryService.startProcedures;


import org.drools.runtime.process.WorkflowProcessInstance;
import java.util.Map;
import java.util.HashMap;
import com.wordpress.salaboy.model.*;
import com.wordpress.salaboy.model.Emergency.EmergencyType;
import com.wordpress.salaboy.messaging.*;
import com.wordpress.salaboy.model.messages.*;


rule "Get Information To Start Procedure"
    salience 20
    ruleflow-group "start process"
    when
        $processInstance: WorkflowProcessInstance()
        $emergency: Emergency()
    then
        SelectedProcedures selectedProcedures = (SelectedProcedures)$processInstance.getVariable("selectedProcedures");
        Call call = (Call)$processInstance.getVariable("call");
        for(int i = 0; i < selectedProcedures.size(); i++){
            Map<String, Object> parameters = new HashMap<String, Object>();
            parameters.put("emergency.id", $emergency.getId());
            MessageFactory.sendMessage(new SelectedProcedureMessage(selectedProcedures.get(i), call.getId(),  parameters));
        }
        
       
end




