package test;

import com.wordpress.salaboy.hospital.*;

query "getAvailableBeds" ()
    Hospital($availableBeds: availableBeds )
end

rule "request bed"
    no-loop
    when
        $hospital: Hospital()
        $bedRequest: RequestBed()
    then
        Patient patient = new Patient();

        System.out.println("Requesting a bed!");    
        kcontext.getKnowledgeRuntime().startProcess("NewPatientCheckIn", null);
        System.out.println("Getting ready for recieving a new patient");
end

rule "assign bed"
    no-loop
    ruleflow-group "assign-bed"
    when
        $hospital: Hospital(availableBeds > 0)
    then
        System.out.println("Assigning a bed...");
        $hospital.setAvailableBeds($hospital.getAvailableBeds()-1);
        update($hospital);
        
end


