package test;
import com.wordpress.salaboy.hospital.*;
import com.wordpress.salaboy.model.roles.*;
import org.drools.runtime.process.WorkflowProcessInstance;

rule "init hospital"
    salience 1
    ruleflow-group "assign-bed"
    when
        not(Hospital())
    then
        System.out.println("Initializing the Hospital ...");
        Hospital hospital = new Hospital();
        hospital.setAvailableBeds(30);
        insert(hospital);
end


rule "assign bed"
    no-loop
    ruleflow-group "assign-bed"
    when
        $hospital: Hospital(availableBeds > 0)
        
    then
        System.out.println("Assigning a bed ...");
        $hospital.setAvailableBeds($hospital.getAvailableBeds()-1);
        update($hospital);
        
end


