package callsHandling;

import com.wordpress.salaboy.model.Emergency;
import com.wordpress.salaboy.call.CallManager;
import org.drools.runtime.process.ProcessInstance;
import java.util.Map;
import java.util.HashMap;
import java.text.SimpleDateFormat;

global CallManager callManager;
global Map ambulances;

rule "Handling Single Emergency Call"
    no-loop true
    lock-on-active true
    when
        $emergency: Emergency()
    then
        java.text.DateFormat df = SimpleDateFormat.getInstance().getDateTimeInstance(SimpleDateFormat.SHORT, SimpleDateFormat.SHORT);
       
        Map<String, Object> parameters = new HashMap<String, Object>();
        parameters.put("emergency", $emergency );
        parameters.put("call.id", $emergency.getCall().getId());
        parameters.put("call.timestamp", df.format($emergency.getCall().getDate()));
        parameters.put("call.phoneNumber", $emergency.getCall().getPhoneNumber());
        ProcessInstance pI = kcontext.getKnowledgeRuntime().startProcess("com.wordpress.salaboy.bpmn2.EmergencyService", parameters);
        $emergency.getCall().setProcessId(pI.getId());
        callManager.incomingCall($emergency.getCall());
        update($emergency);
        insert(pI);
end