package org.plugtree.emergencyservice.callsHandling;

import org.plugtree.training.model.Call;
import org.plugtree.training.model.Emergency;
import org.drools.runtime.process.ProcessInstance;
import org.drools.runtime.process.ProcessInstance;
import org.drools.runtime.process.WorkflowProcessInstance;
import org.drools.workflow.instance.node.WorkItemNodeInstance;
import java.util.Map;
import java.util.HashMap;
import java.text.SimpleDateFormat;

global com.wordpress.salaboy.call.CallManager callManager;
global Map ambulances;

rule "Handling Single Emergency Call"
    when
       $call:  Call()
    then
        
        SimpleDateFormat df = SimpleDateFormat.getInstance().getDateTimeInstance(SimpleDateFormat.SHORT, SimpleDateFormat.SHORT);
        Emergency emergency = new Emergency();
        emergency.setCall($call);
        $call.setProcessId(pI.getId());
        Map<String, Object> parameters = new HashMap<String, Object>();
        parameters.put("emergency", emergency );
        parameters.put("call.id", $call.getId());
        parameters.put("call.timestamp", df.format($call.getDate()));
        parameters.put("call.processId", $call.getProcessId());
        ProcessInstance pI = kcontext.getKnowledgeRuntime().startProcess("org.drools.bpmn2.EmergencyService", parameters);
        callManager.incomingCall($call);
        insert(pI);
end
    