package org.plugtree.emergencyservice.callsHandling;

import org.plugtree.training.model.Call;
import org.plugtree.training.model.Emergency;
import org.drools.runtime.process.ProcessInstance;
import org.drools.runtime.process.ProcessInstance;
import org.drools.runtime.process.WorkflowProcessInstance;
import org.jbpm.workflow.instance.node.WorkItemNodeInstance;
import java.util.Map;
import java.util.HashMap;
import java.text.SimpleDateFormat;

global com.wordpress.salaboy.call.CallManager callManager;

global Map ambulances;

rule "Handling Single Emergency Call"
    no-loop true
    when
  
        $emergency: Emergency()
    then
        
        java.text.DateFormat df = SimpleDateFormat.getInstance().getDateTimeInstance(SimpleDateFormat.SHORT, SimpleDateFormat.SHORT);
       
        Map<String, Object> parameters = new HashMap<String, Object>();
        parameters.put("emergency", $emergency );
        parameters.put("call.id", $emergency.getCall().getId());
        parameters.put("call.timestamp", df.format($emergency.getCall().getDate()));
        parameters.put("call.phoneNumber", $emergency.getCall().getPhoneNumber());
        ProcessInstance pI = kcontext.getKnowledgeRuntime().startProcess("org.drools.bpmn2.EmergencyService", parameters);
        $emergency.getCall().setProcessId(pI.getId());
        callManager.incomingCall($emergency.getCall());
        update($emergency);
        insert(pI);
end
    