package com.wordpress.salaboy.wiimote.drools;

import motej.event.AccelerometerEvent;
import java.util.LinkedList;
import java.util.ArrayList;
import com.wordpress.salaboy.events.WiiMoteEvent;
import com.wordpress.salaboy.ui.MapEventsNotifier;
import com.wordpress.salaboy.EmergencyService;



declare WiiMoteEvent
    @role ( event )
    @expires ( 20s )
end

rule "Patient with no vital sign"
    when
        
        $nextEvents : Number(doubleValue == 235 ) from accumulate( WiiMoteEvent( type == "acc", processed == false, $y: y) over window:time(4s) from entry-point "patientHeartbeats",
        												average($y)) 
    then
        EmergencyService.getInstance().getMapEventsNotifier().notifyMapEventsListeners(MapEventsNotifier.EventType.NO_VITAL_SIGNS, "Warning, patient without vital signs ");
end

rule "Patient heart attack"
    when
        
        $nextEvents : ArrayList(size > 10 ) from collect( WiiMoteEvent( type == "acc", processed == false, $y: y) over window:time(1s) from entry-point "patientHeartbeats") 
    then
        EmergencyService.getInstance().getMapEventsNotifier().notifyMapEventsListeners(MapEventsNotifier.EventType.HEART_ATTACK, "Warning, patient suffering a heart attack ");
end