package org.plugtree.emergencyservice.hospitalselection;

import org.plugtree.training.model.Ambulance;
import org.plugtree.training.model.Emergency;
import org.plugtree.training.model.Emergency.EmergencyType;
import org.plugtree.training.model.Medic;
import org.plugtree.training.model.Medic.MedicSpeciality;
import org.plugtree.training.model.MedicalKit;
import org.plugtree.training.model.Location;
import org.plugtree.training.model.Hospital;
import org.plugtree.training.model.Patient;
import org.drools.runtime.process.WorkflowProcessInstance;
import com.wordpress.salaboy.EmergencyService;
import java.util.Map;
import com.wordpress.salaboy.ui.MapEventsNotifier;


global Map hospitals;


query "getPatient"
    //@TODO add more filters per process/emergency
    patient: Patient()
end


rule "Rank Hospital Speciality that matches EmergencyType"
    
    ruleflow-group "hospital_selection"
    when
        $processInstance: WorkflowProcessInstance()
        $emergency: Emergency($type: type.name)
        //$patient: Patient()
        $ambulance: Ambulance()
        // need to add filters for specialities or based on the priority choose the closest one no matter what type of emergency
        $selectedHospital: Hospital() from accumulate ($hospital: Hospital() from hospitals.values(), 
                                                    init( Hospital selected = null; float distanceX = 0; float distanceY = 0; double best = 1000d;),
                                                    action( float difX = $hospital.getPositionX() - $ambulance.getPositionX(); 
                                                            float difY = $hospital.getPositionY() - $ambulance.getPositionY();                                                            
                                                            double difTotal = Math.sqrt(Math.pow(((double)difX),2d) + Math.pow(((double)difY),2d));
                                                            //System.out.println("Dif Total = "+difTotal+ " for Hospital ="+$hospital.getName());
                                                            //System.out.println("Hospital now = "+$hospital);
                                                            if(difTotal < best){ best = difTotal; selected = $hospital;}
                                                            ),
                                                    reverse(),
                                                    result(selected)
                                                    )
        //@TODO add more filters

    then
        //@TODO use the 
        System.out.println("Hospital Selected"+$selectedHospital);
        EmergencyService.getInstance().getMapEventsNotifier().notifyMapEventsListeners(MapEventsNotifier.EventType.HOSPITAL_SELECTED, $selectedHospital.getId());
        
end



