package org.plugtree.emergencyservice.ambulance;

import org.plugtree.training.model.Ambulance;
import org.plugtree.training.model.Call;
import org.plugtree.training.model.Patient;
import org.plugtree.training.model.Emergency;
import org.plugtree.training.model.Emergency.EmergencyType;
import org.plugtree.training.model.Medic;
import org.plugtree.training.model.Medic.MedicSpeciality;
import org.plugtree.training.model.MedicalKit;
import org.plugtree.training.model.Location;
import org.drools.runtime.process.WorkflowProcessInstance;
import java.util.Map;
import java.util.List;

global Map ambulances;
global Map doctors;

rule "Initialize Emergency"
    ruleflow-group "select_ambulance"
    when
      $processInstance: WorkflowProcessInstance()
      $call: Call()
    then
     System.out.println("Emergency !!!!!@@@@@@@@@  "+$processInstance.getVariable("emergency") +
                             "\n patient.name = " +(String)$processInstance.getVariable("patient.name") +
                             "\n patient.age = " + Integer.valueOf((String)$processInstance.getVariable("patient.age")) +
                             "\n patient.gender = " + (String)$processInstance.getVariable("patient.gender"));
     Emergency emergency = (Emergency)$processInstance.getVariable("emergency");
     Patient patient = new Patient((String)$processInstance.getVariable("patient.name"),
                                Integer.valueOf((String)$processInstance.getVariable("patient.age")),
                                (String)$processInstance.getVariable("patient.gender") );
       emergency.setPatient(patient);
       emergency.setType(EmergencyType.valueOf((String)$processInstance.getVariable("emergency.type")));
       emergency.setCall($call);
       $processInstance.setVariable("patient.id", patient.getId());
       System.out.println("NEW Emergency  "+$processInstance.getVariable("emergency"));
       insert(emergency);
       
end

rule "Fire Emergency"
    ruleflow-group "select_ambulance"
    when
        $processInstance: WorkflowProcessInstance()
        $emergency: Emergency($type : type == EmergencyType.FIRE)
    then
    	
        Ambulance ambulance = (Ambulance)((List)ambulances.get($type)).get(0);
        Medic medic = (Medic)((List)doctors.get(MedicSpeciality.BURNS)).get(0);
        ambulance.setMedicOnBoard(medic);
        $emergency.setAmbulance(ambulance);

        $processInstance.setVariable("doctor.id", medic.getId());
        $processInstance.setVariable("ambulance.id", ambulance.getId());
        //insert(ambulance);
end

rule "Car Crash Emergency"
     ruleflow-group "select_ambulance"
    when
        $processInstance: WorkflowProcessInstance()
        $emergency: Emergency($type: type == EmergencyType.CAR_CRASH)
    then
    	
        Medic medic = (Medic)((List)doctors.get(MedicSpeciality.BONES)).get(0);
        Ambulance ambulance = (Ambulance)((List) ambulances.get($type)).get(0);
        ambulance.setMedicOnBoard(medic);
        $emergency.setAmbulance(ambulance);


        $processInstance.setVariable("doctor.id", medic.getId());
        $processInstance.setVariable("ambulance.id", ambulance.getId());
        
        //insert(ambulance);
end

rule "Heart Attack Emergency"
     ruleflow-group "select_ambulance"
    when
        $processInstance: WorkflowProcessInstance()
        $emergency: Emergency($type: type == EmergencyType.HEART_ATTACK)
    then
    	
        Medic medic = (Medic)((List)doctors.get(MedicSpeciality.REANIMATION)).get(0);
        Ambulance ambulance = (Ambulance)((List) ambulances.get($type)).get(0);
        ambulance.setMedicOnBoard(medic);
        $emergency.setAmbulance(ambulance);

        $processInstance.setVariable("doctor.id", medic.getId());
        $processInstance.setVariable("ambulance.id", ambulance.getId());
        
        //insert(ambulance);
end