package com.wordpress.salaboy.wiimote.drools;

import motej.event.AccelerometerEvent;
import java.util.LinkedList;
import java.util.ArrayList;
import com.wordpress.salaboy.events.WiiMoteEvent;

//declare AccelerometerEvent
//    @role( event )
    
//end

declare WiiMoteEvent
    @role ( event )
end

    #http://wiimotecommande.sourceforge.net/wiimote/index.html


/*rule "Pronounced Y acceleration"
    when
        $e1: AccelerometerEvent($y1: y) from entry-point "wiimote1"
        $e2: AccelerometerEvent(this != $e1, this after[ 0, 50ms ] $e1, $y2: y >= $y1) from entry-point "wiimote1"
        $e3: AccelerometerEvent(this != $e1,this != $e2, this after[ 0, 50ms ] $e2,  $y3: y >= $y2) from entry-point "wiimote1"
        $e4: AccelerometerEvent(this != $e1,this != $e2, this != $e3,this after[ 0, 50ms ] $e3,  $y4: y >= $y3) from entry-point "wiimote1"
    then
        System.out.println("pronounced Y acceleration");
end

rule "Pronounced X acceleration"
    when
        $e1: AccelerometerEvent($x1: x) from entry-point "wiimote1"
        $e2: AccelerometerEvent(this != $e1, this after[ 0, 50ms ] $e1, $x2: x >= $x1) from entry-point "wiimote1"
        $e3: AccelerometerEvent(this != $e1,this != $e2, this after[ 0, 50ms ] $e2,  $x3: x >= $x2) from entry-point "wiimote1"
        $e4: AccelerometerEvent(this != $e1,this != $e2, this != $e3,this after[ 0, 50ms ] $e3,  $x4: x >= $x3) from entry-point "wiimote1"
    then
        System.out.println("pronounced X acceleration");
end

rule "Pronounced Z acceleration"
    when
        $e1: AccelerometerEvent($z1: z) from entry-point "wiimote1"
        $e2: AccelerometerEvent(this != $e1, this after[ 0, 50ms ] $e1, $z2: z >= $z1) from entry-point "wiimote1"
        $e3: AccelerometerEvent(this != $e1,this != $e2, this after[ 0, 50ms ] $e2,  $z3: z >= $z2) from entry-point "wiimote1"
        $e4: AccelerometerEvent(this != $e1,this != $e2, this != $e3,this after[ 0, 100ms ] $e3,  $z4: z >= $z3) from entry-point "wiimote1"
    then
        System.out.println("pronounced X acceleration");
end*/

rule "Mote UP"
    when
        $e1: WiiMoteEvent(type == "acc", processed == false, $x1: y < 120) from entry-point "wiimote1"
          $nextEvents : ArrayList(size > 1)
             from collect( WiiMoteEvent(this != $e1, processed == false, this after[ 0, 200ms ] $e1, $x2: y < 120) from entry-point "wiimote1"
                              ) 
    then
        System.out.println("Mote UP y < 120");
        
        $e1.setProcessed(true);
        update($e1);
        for (Object object : $nextEvents) {
            WiiMoteEvent event = (WiiMoteEvent) object;
            event.setProcessed(true);
            update(event);
        }
end

rule "Mote DOWN"
    when
        $e1: WiiMoteEvent(type == "acc", processed == false, $x1: y > 120) from entry-point "wiimote1"
          $nextEvents : ArrayList(size > 1)
             from collect( WiiMoteEvent(this != $e1, processed == false, this after[ 0, 200ms ] $e1, $x2: y > 120) from entry-point "wiimote1"
                              ) 
    then
        System.out.println("Mote DOWN  y > 120");
        
        $e1.setProcessed(true);
        update($e1);
        for (Object object : $nextEvents) {
            WiiMoteEvent event = (WiiMoteEvent) object;
            event.setProcessed(true);
            update(event);
        }
end

/*rule "Right Arrow"
    when
        $e1: WiiMoteEvent(type == "acc", processed == false, x > 245) from entry-point "wiimote1"
          $nextEvents : ArrayList(size > 1)
             from collect( WiiMoteEvent(this != $e1, processed == false, this after[ 0, 30ms ] $e1,  x > 245) from entry-point "wiimote1"
                              )
    then
        System.out.println("Right Arrow");

        $e1.setProcessed(true);
        update($e1);
        for (Object object : $nextEvents) {
            WiiMoteEvent event = (WiiMoteEvent) object;
            event.setProcessed(true);
            update(event);
        }
end


*/