/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserUI.java
 *
 * Created on Nov 2, 2010, 4:45:08 PM
 */

package com.wordpress.salaboy.ui;

import com.wordpress.salaboy.TaskServerDaemon;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.drools.SystemEventListenerFactory;
import org.drools.task.AccessType;
import org.drools.task.Task;
import org.drools.task.service.ContentData;
import org.drools.task.service.TaskClient;
import org.drools.task.service.mina.MinaTaskClientConnector;
import org.drools.task.service.mina.MinaTaskClientHandler;
import org.drools.task.service.responsehandlers.BlockingGetTaskResponseHandler;
import org.drools.task.service.responsehandlers.BlockingTaskOperationResponseHandler;
import org.plugtree.training.model.Call;

/**
 *
 * @author salaboy
 */
public class UserUI extends javax.swing.JFrame {
    
    
    public static Map<Long, Call> calls = new HashMap<Long, Call>();
    private TaskClient client;
    private static final long DEFAULT_WAIT_TIME = 5000;
    private Task currentTask;
    private SlickBasicGame game;
    /** Creates new form UserUI */
    public UserUI() {
        initComponents();
        initTaskServer();
        initTaskClient();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJTabbedPane = new javax.swing.JTabbedPane();
        phoneCallsjPanel = new javax.swing.JPanel();
        phoneCallsJScrollPane = new javax.swing.JScrollPane();
        phoneCallsJTable = new javax.swing.JTable();
        newEmergencyPhoneCallJButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        refreshJButton = new javax.swing.JButton();
        emergencyInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        genderjComboBox = new javax.swing.JComboBox();
        emergencyTypeJComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ageJTextField = new javax.swing.JTextField();
        chooseAmbuelanceJButton = new javax.swing.JButton();
        locationjTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ambulancejPanel = new javax.swing.JPanel();
        sendAmbulancejButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ambulancejList = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        medicalKitsJInternalFrame = new javax.swing.JInternalFrame();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        doctorsjList = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        pickUpPatientjButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        hospitalJPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        managerjPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        phoneCallsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Alert"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        phoneCallsJTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        phoneCallsJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rowClick(evt);
            }
        });
        phoneCallsJScrollPane.setViewportView(phoneCallsJTable);

        newEmergencyPhoneCallJButton.setText("New Emergency Phone Call");
        newEmergencyPhoneCallJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEmergencyPhoneCallJButtonActionPerformed(evt);
            }
        });

        jLabel11.setText("Incoming Calls");

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout phoneCallsjPanelLayout = new org.jdesktop.layout.GroupLayout(phoneCallsjPanel);
        phoneCallsjPanel.setLayout(phoneCallsjPanelLayout);
        phoneCallsjPanelLayout.setHorizontalGroup(
            phoneCallsjPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(phoneCallsjPanelLayout.createSequentialGroup()
                .add(20, 20, 20)
                .add(phoneCallsjPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(phoneCallsjPanelLayout.createSequentialGroup()
                        .add(229, 229, 229)
                        .add(jLabel11))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, phoneCallsjPanelLayout.createSequentialGroup()
                        .add(refreshJButton)
                        .add(260, 260, 260))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, phoneCallsJScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE))
                .add(83, 83, 83))
            .add(phoneCallsjPanelLayout.createSequentialGroup()
                .add(171, 171, 171)
                .add(newEmergencyPhoneCallJButton)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        phoneCallsjPanelLayout.setVerticalGroup(
            phoneCallsjPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(phoneCallsjPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .add(jLabel11)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(phoneCallsJScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 355, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(28, 28, 28)
                .add(refreshJButton)
                .add(18, 18, 18)
                .add(newEmergencyPhoneCallJButton)
                .add(48, 48, 48))
        );

        mainJTabbedPane.addTab("Phone Calls", phoneCallsjPanel);

        jLabel1.setText("Name: ");

        nameJTextField.setEnabled(false);

        jLabel2.setText("Gender:");

        genderjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MALE", "FEMALE" }));
        genderjComboBox.setEnabled(false);

        emergencyTypeJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FIRE", "CAR CRASH", "STROKE", "ASSAULT" }));
        emergencyTypeJComboBox.setEnabled(false);

        jLabel3.setText("Emergency Type:");

        jLabel5.setText("Age:");

        ageJTextField.setEnabled(false);

        chooseAmbuelanceJButton.setText("Choose Ambulance");
        chooseAmbuelanceJButton.setEnabled(false);
        chooseAmbuelanceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseAmbuelanceJButtonActionPerformed(evt);
            }
        });

        locationjTextField.setEnabled(false);

        jLabel12.setText("Location:");

        org.jdesktop.layout.GroupLayout emergencyInfoLayout = new org.jdesktop.layout.GroupLayout(emergencyInfo);
        emergencyInfo.setLayout(emergencyInfoLayout);
        emergencyInfoLayout.setHorizontalGroup(
            emergencyInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(emergencyInfoLayout.createSequentialGroup()
                .add(72, 72, 72)
                .add(emergencyInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel1)
                    .add(jLabel2)
                    .add(jLabel3)
                    .add(jLabel5)
                    .add(jLabel12))
                .add(18, 18, 18)
                .add(emergencyInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(ageJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(emergencyInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, genderjComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, emergencyTypeJComboBox, 0, 144, Short.MAX_VALUE)
                        .add(chooseAmbuelanceJButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 213, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(emergencyInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, locationjTextField)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, nameJTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        emergencyInfoLayout.setVerticalGroup(
            emergencyInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(emergencyInfoLayout.createSequentialGroup()
                .add(75, 75, 75)
                .add(emergencyInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(locationjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel12))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(emergencyInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(nameJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(emergencyInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(genderjComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(15, 15, 15)
                .add(emergencyInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(emergencyTypeJComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(emergencyInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(ageJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(chooseAmbuelanceJButton)
                .addContainerGap(271, Short.MAX_VALUE))
        );

        mainJTabbedPane.addTab("Emergency Info", emergencyInfo);

        sendAmbulancejButton.setText("Send Ambulance");
        sendAmbulancejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendAmbulancejButtonActionPerformed(evt);
            }
        });

        ambulancejList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Ambulance S00001", "Ambulance S00002", "Ambulance S00003", "Ambulance S00004" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ambulancejList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectedAmbulance(evt);
            }
        });
        jScrollPane2.setViewportView(ambulancejList);

        jLabel6.setText("Available Ambulances");

        medicalKitsJInternalFrame.setTitle("Medical Kits");
        medicalKitsJInternalFrame.setVisible(true);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/older/collision.png"))); // NOI18N

        org.jdesktop.layout.GroupLayout medicalKitsJInternalFrameLayout = new org.jdesktop.layout.GroupLayout(medicalKitsJInternalFrame.getContentPane());
        medicalKitsJInternalFrame.getContentPane().setLayout(medicalKitsJInternalFrameLayout);
        medicalKitsJInternalFrameLayout.setHorizontalGroup(
            medicalKitsJInternalFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(medicalKitsJInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(413, Short.MAX_VALUE))
        );
        medicalKitsJInternalFrameLayout.setVerticalGroup(
            medicalKitsJInternalFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(medicalKitsJInternalFrameLayout.createSequentialGroup()
                .add(34, 34, 34)
                .add(jLabel8)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        doctorsjList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Doctor D0001", "Doctor D0002" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(doctorsjList);

        jLabel7.setText("Available Doctors");

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout ambulancejPanelLayout = new org.jdesktop.layout.GroupLayout(ambulancejPanel);
        ambulancejPanel.setLayout(ambulancejPanelLayout);
        ambulancejPanelLayout.setHorizontalGroup(
            ambulancejPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ambulancejPanelLayout.createSequentialGroup()
                .add(ambulancejPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(ambulancejPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(sendAmbulancejButton))
                    .add(ambulancejPanelLayout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(ambulancejPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel6)
                            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                            .add(medicalKitsJInternalFrame)
                            .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 370, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel7)))
                    .add(ambulancejPanelLayout.createSequentialGroup()
                        .add(171, 171, 171)
                        .add(jButton3)))
                .addContainerGap())
        );
        ambulancejPanelLayout.setVerticalGroup(
            ambulancejPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, ambulancejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jButton3)
                .add(22, 22, 22)
                .add(jLabel6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 14, Short.MAX_VALUE)
                .add(medicalKitsJInternalFrame, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(14, 14, 14)
                .add(jLabel7)
                .add(18, 18, 18)
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(sendAmbulancejButton)
                .addContainerGap())
        );

        mainJTabbedPane.addTab("Ambulance", ambulancejPanel);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Go to A8 and D8");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel4.setText("Directions");

        pickUpPatientjButton.setText("Pick Up Patient");
        pickUpPatientjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickUpPatientjButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel4)
                .add(516, 516, 516))
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 374, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(pickUpPatientjButton)
                .addContainerGap(360, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(16, 16, 16)
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(pickUpPatientjButton)
                .addContainerGap(384, Short.MAX_VALUE))
        );

        mainJTabbedPane.addTab("Driver", jPanel2);

        jLabel9.setText("jLabel9");

        jTextField1.setText("jTextField1");

        jLabel10.setText("jLabel10");

        jTextField2.setText("jTextField2");

        jButton1.setText("Send Report - Select Hospital");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel10)
                            .add(jLabel9))
                        .add(18, 18, 18)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(jButton1)))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(136, 136, 136)
                .add(jButton1)
                .addContainerGap(290, Short.MAX_VALUE))
        );

        mainJTabbedPane.addTab("Doctor", jPanel3);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Gender", "Emergency Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectPatientToAccept(evt);
            }
        });
        jScrollPane4.setViewportView(jTable1);

        jButton2.setText("Accept Selected Patient");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout hospitalJPanelLayout = new org.jdesktop.layout.GroupLayout(hospitalJPanel);
        hospitalJPanel.setLayout(hospitalJPanelLayout);
        hospitalJPanelLayout.setHorizontalGroup(
            hospitalJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, hospitalJPanelLayout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .add(jButton2)
                .add(214, 214, 214))
            .add(hospitalJPanelLayout.createSequentialGroup()
                .add(200, 200, 200)
                .add(jScrollPane4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );
        hospitalJPanelLayout.setVerticalGroup(
            hospitalJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(hospitalJPanelLayout.createSequentialGroup()
                .add(43, 43, 43)
                .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 257, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButton2)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        mainJTabbedPane.addTab("Hospital", hospitalJPanel);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 468, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 495, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Reports", jPanel1);

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 468, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 495, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Activity Console", jPanel4);

        org.jdesktop.layout.GroupLayout managerjPanelLayout = new org.jdesktop.layout.GroupLayout(managerjPanel);
        managerjPanel.setLayout(managerjPanelLayout);
        managerjPanelLayout.setHorizontalGroup(
            managerjPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(managerjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addContainerGap())
        );
        managerjPanelLayout.setVerticalGroup(
            managerjPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(managerjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Reports");

        mainJTabbedPane.addTab("Manager", managerjPanel);

        fileMenu.setText("File");

        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setText("Save As ...");
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setText("Edit");

        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setText("Help");

        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(mainJTabbedPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 536, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(mainJTabbedPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void newEmergencyPhoneCallJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEmergencyPhoneCallJButtonActionPerformed
        //Start Emergency Business Process
        
        
    }//GEN-LAST:event_newEmergencyPhoneCallJButtonActionPerformed

    private void rowClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rowClick
        
        mainJTabbedPane.setSelectedIndex(1);
        locationjTextField.setEnabled(true);
        nameJTextField.setEnabled(true);
        emergencyTypeJComboBox.setEnabled(true);
        ageJTextField.setEnabled(true);
        chooseAmbuelanceJButton.setEnabled(true);
        genderjComboBox.setEnabled(true);
        System.out.println("ID from EVT"+evt.getID());
        int selected = phoneCallsJTable.rowAtPoint(evt.getPoint());
        
        currentTask = getTask(Long.parseLong(phoneCallsJTable.getModel().getValueAt(selected, 0).toString()));
        BlockingTaskOperationResponseHandler responseHandler = new BlockingTaskOperationResponseHandler();
        client.start(currentTask.getId(), "operator", responseHandler); 
        
        
    }//GEN-LAST:event_rowClick

    private void chooseAmbuelanceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseAmbuelanceJButtonActionPerformed
        ObjectOutputStream out = null;
        try {
            
            // data.setCon
            Map<String, Object> info = new HashMap<String, Object>();
            System.out.println("LocationUI = "+locationjTextField.getText());
            System.out.println("ageUI = "+ageJTextField.getText());
            System.out.println("nameUI = "+nameJTextField.getText());
            System.out.println("genderUI = "+genderjComboBox.getModel().getSelectedItem());
            System.out.println("typeUI = "+emergencyTypeJComboBox.getModel().getSelectedItem());
            info.put("emergency.location",locationjTextField.getText());
            info.put("emergency.name",nameJTextField.getText());
            info.put("emergency.type",emergencyTypeJComboBox.getModel().getSelectedItem()) ; // emergencyTypeJComboBox.getSelectedIndex())
            info.put("emergency.age",ageJTextField.getText());
            info.put("emergency.gender",genderjComboBox.getModel().getSelectedItem());
            
            ContentData result = new ContentData();
            result.setAccessType(AccessType.Inline);
            result.setType("java.util.Map");
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            out = new ObjectOutputStream(bos);
            out.writeObject(info);
            out.close();
            result.setContent(bos.toByteArray());
            //Complete human Task
            client.complete(currentTask.getId(), "operator", result, null);
            //Show ambulance tab.. with all the selected items
            mainJTabbedPane.setSelectedIndex(2);
        } catch (IOException ex) {
            Logger.getLogger(UserUI.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                out.close();
            } catch (IOException ex) {
                Logger.getLogger(UserUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    }//GEN-LAST:event_chooseAmbuelanceJButtonActionPerformed

    private void selectedAmbulance(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectedAmbulance
        // TODO add your handling code here:
        //From the list of selected ambulance show the ambulance details
        
    }//GEN-LAST:event_selectedAmbulance

    private void sendAmbulancejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendAmbulancejButtonActionPerformed
        // TODO add your handling code here:
        //PUT the ambulance in the map
        mainJTabbedPane.setSelectedIndex(2);
        
        
    }//GEN-LAST:event_sendAmbulancejButtonActionPerformed

    private void pickUpPatientjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickUpPatientjButtonActionPerformed
        // TODO add your handling code here:
        //create dotor human task to report the situation
        mainJTabbedPane.setSelectedIndex(3);
    }//GEN-LAST:event_pickUpPatientjButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //Accept selected patient. Move to report/END
        mainJTabbedPane.setSelectedIndex(5);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void selectPatientToAccept(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectPatientToAccept
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_selectPatientToAccept

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // send report and select hospital. End Human Task
        mainJTabbedPane.setSelectedIndex(4);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        phoneCallsJTable.removeAll();
        for(Long key : calls.keySet()){
            ((DefaultTableModel)phoneCallsJTable.getModel()).addRow(new String[]{key.toString(), calls.get(key).getDate().toString()});
        }
         
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        updateUIMap();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JTextField ageJTextField;
    private javax.swing.JList ambulancejList;
    private javax.swing.JPanel ambulancejPanel;
    private javax.swing.JButton chooseAmbuelanceJButton;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JList doctorsjList;
    private javax.swing.JMenu editMenu;
    private javax.swing.JPanel emergencyInfo;
    private javax.swing.JComboBox emergencyTypeJComboBox;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JComboBox genderjComboBox;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JPanel hospitalJPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField locationjTextField;
    private javax.swing.JTabbedPane mainJTabbedPane;
    private javax.swing.JPanel managerjPanel;
    private javax.swing.JInternalFrame medicalKitsJInternalFrame;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JButton newEmergencyPhoneCallJButton;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JScrollPane phoneCallsJScrollPane;
    private javax.swing.JTable phoneCallsJTable;
    private javax.swing.JPanel phoneCallsjPanel;
    private javax.swing.JButton pickUpPatientjButton;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JButton sendAmbulancejButton;
    // End of variables declaration//GEN-END:variables

    private void initTaskServer() {
        final TaskServerDaemon taskServerDaemon = new TaskServerDaemon();
        
        Runtime.getRuntime().addShutdownHook(new Thread() {
            public void run() { 
                System.out.println("\n");
                taskServerDaemon.stopServer();
                System.out.println("server stoped...");
            }
         });

        taskServerDaemon.startServer();
        System.out.println("server started... (ctrl-c to stop it)");
    }

    private void initTaskClient() {
        client = new TaskClient(new MinaTaskClientConnector("client 1",
        new MinaTaskClientHandler(SystemEventListenerFactory.getSystemEventListener())));
        boolean connected = client.connect("127.0.0.1", 9123);
        
        
        while(!connected){
            try {
                Thread.sleep(2000);
            } catch (InterruptedException ex) {
                Logger.getLogger(UserUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            connected = client.connect("127.0.0.1", 9123);
            
        }
    }
    
    public Task getTask(Long workItemId) {
		BlockingGetTaskResponseHandler getTaskResponseHandler = new BlockingGetTaskResponseHandler();
                client.getTaskByWorkItemId(workItemId, getTaskResponseHandler);
		Task task = getTaskResponseHandler.getTask();
		return task;
    }

   

    void setUIMap(SlickBasicGame game) {
        this.game = game;
    }

    private void updateUIMap() {
        System.out.println("Firing all the rules!!!");
        this.game.ksession.fireAllRules();
    }

    

}
