/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WiiMoteOptions.java
 *
 * Created on Dec 6, 2010, 7:47:32 AM
 */

package com.wordpress.salaboy.ui;

import com.intel.bluetooth.BlueCoveConfigProperties;
import com.wordpress.salaboy.events.SimpleMoteFinder;
import motej.Mote;
import motej.event.AccelerometerEvent;
import motej.event.AccelerometerListener;
import motej.event.MoteDisconnectedEvent;
import motej.event.MoteDisconnectedListener;
import motej.request.ReportModeRequest;

/**
 *
 * @author salaboy
 */
public class WiiMoteOptions extends javax.swing.JFrame {
    private Mote mote = null;
    private SlickBasicGame game = null;
    /** Creates new form WiiMoteOptions */
    public WiiMoteOptions(SlickBasicGame game) {
        initComponents();
        this.game = game;
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(39, 39, 39)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(93, 93, 93)
                .add(jButton1)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(54, 54, 54)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(90, 90, 90)
                        .add(jButton1)))
                .addContainerGap(346, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        initWiiMote();
    }//GEN-LAST:event_jButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    private void initWiiMote() {
        System.setProperty(BlueCoveConfigProperties.PROPERTY_JSR_82_PSM_MINIMUM_OFF, "true");
        SimpleMoteFinder simpleMoteFinder = new SimpleMoteFinder();
        mote = simpleMoteFinder.findMote();
        if(mote == null){
            jTextArea1.insert("Wii mote not found! ", 0);
        }
        System.out.println("founded wiimote" + mote);
        AccelerometerListener<Mote> listener = new AccelerometerListener<Mote>()   {

            public void accelerometerChanged(AccelerometerEvent<Mote> evt) {
                int y = evt.getY();
                if (y > 225) {
                    jTextArea1.insert("sended " + y + " heartbeat\n", 0);
                    
                    if (game.getAmbulanceMonitorService() != null) {
                        System.out.println("sended " + y + " heartbeat");
                        game.getAmbulanceMonitorService().sendNotification(y, y, y);
                    }
                    
                }
            }
            
            
        };
        MoteDisconnectedListener<Mote> disconnectedListener = new MoteDisconnectedListener<Mote>(){

            @Override
            public void moteDisconnected(MoteDisconnectedEvent<Mote> mde) {
                System.out.println("WII MOTE DISCONECTED!!!!!!");
                jTextArea1.insert("Wii MOTE DISCONECTED!!!!\n", 0);
            }
        
            
        };
        mote.setReportMode(ReportModeRequest.DATA_REPORT_0x31);
        mote.addMoteDisconnectedListener(disconnectedListener);
        mote.addAccelerometerListener(listener);
        

    }
}
